apiVersion: resource-management.tikalk.com/v1alpha1
kind: ResourceManager
metadata:
  name: resource-manager-sample-2
  namespace: default
spec:
  disabled: false
  dry-run: false
  resourceKind: "Deployment"
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - { key: tier, operator: In, values: [ cache ] }
      - { key: environment, operator: NotIn, values: [ dev, dev2 ] }
  action: delete
  expiration:
#    at: 18:57
    after: "1m"
