apiVersion: resource-management.tikalk.com/v1alpha1
kind: ResourceManager
metadata:
  name: resource-manager-sample
  namespace: default
spec:
  disabled: false
  dry-run: false
  resourceKind: "Namespace"
  selector:
    matchLabels:
      component: redis
    matchExpressions:
      - { key: tier, operator: In, values: [ cache ] }
      - { key: environment, operator: NotIn, values: [ dev, dev2 ] }
  expiration:
#    at: 18:57
    after: "2m"