apiVersion: resource-management.tikalk.com/v1alpha1
kind: ResourceManager
metadata:
  name: resource-manager-sample
  namespace: default
spec:
  disabled: false
  dry-run: false
  resourceKind: "Namespace"
  selector:
    matchLabels:
      component: redis
    matchExpressions:
      - { key: tier, operator: In, values: [ cache ] }
      - { key: environment, operator: NotIn, values: [ dev, dev2 ] }
#  namespaceSelector: {}
#  namespaceSelector:
#    matchLabels:
#      component: redis
#    matchExpressions:
#      - { key: tier, operator: In, values: [ cache ] }
#      - { key: environment, operator: NotIn, values: [ dev ] }
#  action: delete
  action: patch
  actionParam: '{"metadata":{"annotations":{"resource-management.tikalk.com/patched":"true"}}}'

  expiration:
#    at: 18:57
    timeframe: "2m"
  # OR
  # - type: time
  #   interval: daily
  #   time: "20:59:59"
#status:
