apiVersion: resource-management.tikalk.com/v1alpha1
kind: ResourceManager
metadata:
  name: resource-manager-sample
spec:
  active: true
  dry-run: false
  resources: "namespace"
  selector:
    matchLabels:
      name: managed-namespace1
  action: "delete"
  condition:
  - type: timeframe
    hour: "17:28"

