apiVersion: resource-management.tikalk.com/v1alpha1
kind: ResourceManager
metadata:
  name: resource-manager-sample
spec:
  disabled: false
  dry-run: false
  resource:
    kind: "Namespace"
    selector:
      matchLabels:
        component: redis
      matchExpressions:
        - { key: tier, operator: In, values: [ cache ] }
        - { key: environment, operator: NotIn, values: [ dev, dev2 ] }
#    namespaceSelector:
#      matchLabels:
#        component: redis
#      matchExpressions:
#        - { key: tier, operator: In, values: [ cache ] }
#        - { key: environment, operator: NotIn, values: [ dev ] }
  action: "NONE"
  condition:
  - type: expiry
    after: "1m"
  # OR
  # - type: time
  #   interval: daily
  #   time: "20:59:59"
#status:
