apiVersion: resource-management.tikalk.com/v1alpha1
kind: ResourceManager
metadata:
  name: resource-manager-sample
spec:
  active: true
  dry-run: false
  resources: "deployment"
  selector:
    matchLabels:
      tobedeleted: yes
  action: "delete"
  condition:
  - type: expiry
    after: "1m"
  # OR
  # - type: time
  #   interval: daily
  #   time: "20:59:59"
#status:
