apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-manager
  labels:
    app: resource-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-manager
  template:
    metadata:
      labels:
        app: resource-manager
    spec:
      containers:
      - name: resource-manager
        image: resource_manager