name: CI using Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Install dependencies
      run: make
      
    - name: build docker image
      run: IMG=ghcr.io/controller:latest make docker-build
      
    - name: push docker image
      run: IMG=ghcr.io/controller:latest make docker-push
