name: CI using Makefile

on:
  push:
    branches:
      - main
      - docker-build
  pull_request:
    branches: 
      - main
      - docker-build

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Install dependencies
      run: make
      
    - name: build docker image
      run: IMG=ghcr.io/${{ github.repository_owner }}/controller:latest make docker-build
      
    - name: push docker image
      run: IMG=ghcr.io/${{ github.repository_owner }}/controller:latest make docker-push
