name: Release Charts

on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      
      - name: custom packaging
        run: |
          VERSION=${{github.ref_name}}
          rm -rf packages
          mkdir -p packages
          helm package Charts/resource-manager-operator --app-version=${VERSION:1} --version=${VERSION:1} --destination=packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
