name: Release Charts

on:
  push:
    branches:
      - main
      - test-release-workflow

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: charts/resource-manager-operator
          charts_repo_url: https://tikalk.github.io/resource-manager
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
