name: CI using Makefile

on:
  push:
    branches:
      - main
      - docker-build
  pull_request:
    branches: 
      - main
      - docker-build
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: make
      
    - name: Test and build docker image
      run: IMG=ghcr.io/${{ github.repository_owner }}/resource-manager:${{github.sha}} make docker-build
      
    - name: Push docker image
      run: IMG=ghcr.io/${{ github.repository_owner }}/resource-manager:${{github.sha}} make docker-push